name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0  # Specify the exact version

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: '157.173.218.79'

    - name: Copy files via SSH
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@157.173.218.79:/path_to_your_project

    - name: SSH and execute deployment
      run: |
        ssh root@157.173.218.79 << 'EOF'
          cd /path_to_your_project
          npm install
          pm2 restart all  # For Node.js projects using PM2
        EOF
